# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
#Documentation configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html # swagger-ui custom path
  api-docs:
    path: /v3/api-docs.yaml
# Logging configuration
logging:
  pattern:
    console: "%d %-5Level %logger : %msg%n"
  level:
    com.example.demowithtests.service: info
    com.example.demowithtests.web: info
    org.springframework: warn
    org.hibernate: info
    org.apache.catalina.core: warn
# Server configuration
server:
  port: 8088 #set your port