create table users
(
    id          bigint generated by default as identity
        primary key,
    name        varchar,
    email       varchar,
    country     varchar,
    gender      varchar,
    is_deleted  boolean,
    passport_id integer
        constraint fkddyjnd93b8x7gdng15k7g429p
            references passports
);

create table passports
(
    id            serial
        primary key,
    birth_date    date,
    first_name    varchar(255),
    second_name   varchar(255),
    serial_number uuid,
    is_free       boolean
);